title: Ethan Bensadoun
theme: jekyll-theme-minimal
description: [This page is dedicated to showcasing my passion and skills for data science. My work 
integrates statistical analysis and machine learning with data visualization to extract meaningful 
insights from data and drive impactful results. Feel free to access my github repositories to look 
at some of the projects I worked on in the last few years.]



